CREATE TABLE IF NOT EXISTS meals_list (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    meal_name VARCHAR(100) NOT NULL,
    img_url TEXT NOT NULL,
    ingredients TEXT NOT NULL,
    chef TEXT NOT NULL,
    cuisine_id INT,
    CONSTRAINT fk_cuisine
        FOREIGN KEY(cuisine_id)
            REFERENCES cuisines(id)
);