BEGIN;

INSERT INTO meals_list
    (meal_name, img_url, ingredients, chef, origin)
VALUES
('Asian-Style Chicken Orzo Salad', 
'https://lfuen.github.io/laCarte/images/meals/orzo.jpg',
('Edamame',
'Orzo',
'Chicken',
'Onions',
'Pepper',
'Vegetable Oil',
'Sesame Oil',
'Ginger',
'Rice Wine Vinegar',
'Soy Sauce',
'Hoisin Sauce',
'Almonds'),
('Johnathan', 'Francesca', 'Christian', 'Madelyn'),
'Asian'),

('Baba Ghanoush',
'https://lfuen.github.io/laCarte/images/meals/baba.jpg',
('Eggplant',
'Flaxseed Oil',
'Garlic',
'Lemon Juice',
'Cumin',
'Tahini',
'Extra-Virgin Olive Oil',
'Pine Nuts',
'Parsley',
'Paprika',
'Salt',
'Black Pepper'),
('Johnathan', 'Joaquin', 'Christian'),
'Middle Eastern'),

('Bibimbap',
'https://lfuen.github.io/laCarte/images/meals/bibimbap.jpg',
('Garlic',
'Ginger',
'Fish Sauce',
'Gochujang Chili Paste',
'Sugar',
'Rice Wine Vinegar',
'Sesame',
'Cabbage',
'Cucumber',
'Bean Sprouts',
'Soy Sauce',
'Sirloin',
'Sesame Oil',       
'Carrot',
'Spinach',
'Sunflower Oil',
'Eggs'),
('Johnathan', 'Francesca', 'Christian', 'Madelyn'),
'Asian'),

('Butter Chicken with Spinach',
'https://lfuen.github.io/laCarte/images/meals/butterChicken.jpg',
('Spinach',
'Garlic',
'Yogurt',
'Almonds',
'Garams Masala',
'Five-Spice Indian Powder',
'Cinnamon',
'Cardamom',
'Ginger',
'Tomatoes',
'Salt',
'Chicken',
'Clarified Butter',
'Onions',
'Coconut Milk',
'Vegetable Stock'),
('Johnathan', 'Christian', 'Madelyn'),	
'Indian'),

('Calamari and Figueras Onion',
'https://lfuen.github.io/laCarte/images/meals/calamari.jpg',
('Squid',
'Onions',
'Wine',
'Tomato Sauce',
'Butter'),	
('Johnathan', 'Francesca'),
'Spanish'),

('Camarones del Sur',
'https://lfuen.github.io/laCarte/images/meals/camarones.jpg',
('Salsa Encebichada',
'Hot Ceviche',
'Andean Pearls',
'Onions',
'Coriander',
'Colored Aji Limo',
'Green Onions',
'Aji Amarillo Paste',
'Garlic Paste',
'Shrimp Broth',
'Orange Juice',
'Aji Limo',
'Chopped Coriander',
'Iodized Salt',
'Lemon Juice',
'Panca de Choclo',
'Potatoes',
'Arracacha',
'Pink Potatoes',
'Zapallo de Carga',
'Cassava',
'Purple Corn Infusion',
'Vegetable Broth',
'Salt',
'Red Onions',
'Garlic',
'Leeks',
'Tomatoes',
'Shrimp',
'Vegetable Oil'),
('Johnathan', 'Francesca', 'Joaquin'),
'Latin American'),

('Ceviche',
'https://lfuen.github.io/laCarte/images/meals/ceviche.jpg',
('Corvina Filet',
'Aji Limo',
'Peruvian Lemons',
'Red Spanish Onions',
'Fish Broth',
'Salt',
'Pepper'),
('Johnathan', 'Francesca', 'Joaquin'),
'Latin American'),

('Chicken Po Boy',
'https://lfuen.github.io/laCarte/images/meals/poBoy.jpg',
('Cabbage',
'Carrots',
'Mint',
'Coriander',
'Serrano Chili',
'Lime Juice',
'Olive Oil',
'Salt',
'Flour',
'Cornmeal',
'Cayenne Pepper',
'Buttermilk',
'Eggs',
'Chicken Breasts',
'Vegetable Oil',
'Mayonnaise'),
('Johnathan', 'Christian', 'Madelyn'),	
'American'),

('Chicken Tikka Masala',
'https://lfuen.github.io/laCarte/images/meals/tikkaMasala.jpg',
('Chicken',
'Lemon',
'Salt',
'Pepper',
'Ginger',
'Garlic',
'Yogurt',
'Vegetable Oil',
'Salt',
'Paprika',
'Cumin',
'Black Pepper',
'Chili Powder',
'Turmeric',
'Cilantro',
'Rice'),
('Johnathan', 'Christian', 'Madelyn'),
'Indian'),

('Chili Pork Adobo',
'https://lfuen.github.io/laCarte/images/meals/porkAdobo.jpg',
('Pork',
'Vegetable Oil',
'Onions',
'Garlic',
'Red Chili',
'Paprika',
'Tomatoes',
'Meat Stock',
'Lemon',
'Oregano',
'Olive Oil',
'Rice',
'Saffron'),
('Johnathan', 'Francesca'),
'Spanish'),

('Chili Sin Carne',
'https://lfuen.github.io/laCarte/images/meals/chili.jpg',
('Vegetarian Mince',
'Oil',
'Garlic',
'Shallots',
'Carrots',
'Tomato Puree',
'Red Chili',
'Green Chili',
'Red Kidney Beans',
'Chickpeas',
'Tomatoes',
'Vegetable Stock',
'Oregano',
'Salt',
'Pepper',
'Cayenne Pepper',
'Basmati Rice'),
('Johnathan', 'Francesca', 'Joaquin', 'Christian', 'Madelyn'),
'Mexican'),

('Cobb Salad',
'https://lfuen.github.io/laCarte/images/meals/cobb.jpg',
('Chicken Breast',
'Romaine Heart',
'Radicchio',
'Smoked Bacon',
'Bleu Cheese',
'Apples',
'Sundried Cranberries',
'Pecans',
'Mayonnaise',
'Apple Juice',
'Apple-Cider Vinegar',
'Honey',
'Rosemary',
'Savory',
'Pecans',
'Butter',
'Brown Sugar'),
('Johnathan', 'Christian', 'Madelyn'),
'American'),

('Coconut Soup with Chicken',
'https://lfuen.github.io/laCarte/images/meals/coconutSoup.jpg',
('Oil',
'Onions',
'Garlic',
'Ginger',
'Lemongrass',
'Red Chili Peppers',
'Chicken',
'Coconut Milk',
'Chicken Breast',
'Lime',
'Soy Sauce',
'Fish Sauce',
'Sugar',
'Lime Juice'),
('Johnathan', 'Joaquin', 'Christian', 'Madelyn'),
'Thai'),

('Coq Au Vin',
'https://lfuen.github.io/laCarte/images/meals/coqAuVin.jpg',
('Chicken',
'Flour',
'Cognac',
'Red Wine',
'Carrot',
'Onion',
'Parsley',
'Bayleaf',      
'Thyme',
'Garlic',
'Pepper',
'Butter'),
('Joaquin', 'Christian'),
'French'),

('Cuban Plantains with Rice and Olives',
'https://lfuen.github.io/laCarte/images/meals/cuban.jpg',
('Sofrito',
'Olives',
'Sazon',
'Rice',
'Plantains'),
('Johnathan', 'Francesca', 'Joaquin'),
'Latin American'),

('Duck Confit with Shallots',
'https://lfuen.github.io/laCarte/images/meals/duckConfit.jpg',
('Duck',
'Shallots',
'Salt',
'Peppercorns',
'Rosemary',
'Honey',
'Duck Fat',
'White Bread'), 
('Joaquin', 'Christian'),
'French'),

('Eggplant Moussaka with Sheeps Milk Cheese',
'https://lfuen.github.io/laCarte/images/meals/eggplant.jpg',
('Olive Oil',
'Aubergines (eggplant)',
'Onions',
'Minced Beef',
'Tomatoes',
'Dry White Wine',
'Parsley',
'Oregano',      
'Breadcrumbs',
'Graviera Cheese',
'Gruyere Cheese',
'Butter',
'Flour',
'Milk',
'Nutmeg',
'Lemon Juice',
'Egg',
'Sheeps Cheese'),
('Johnathan', 'Francesca', 'Joaquin', 'Madelyn'),
'Greek'),

('Fajitas with Beef',
'https://lfuen.github.io/laCarte/images/meals/fajita.jpg',
('Steak',
'Sunflower Oil',
'Seasoning',
'Onions',
'Green Peppers',
'Lime',
'Tortillas',
'Sour Cream',
'Cayenne Pepper',
'Chili Sauce'),
('Johnathan', 'Francesca', 'Joaquin', 'Christian', 'Madelyn'),
'Mexican'),

('Flautas',
'https://lfuen.github.io/laCarte/images/meals/flautas.jpg',
('Chicken',
'Corn Tortillas',
'Vegetable Oil',
'Lettuce',
'Onions',
'Tomatoes',
'Salt',
'Cheddar Cheese',
'Eggs',
'Marjoram',
'Bread'),
('Johnathan', 'Francesca', 'Joaquin', 'Christian', 'Madelyn'),
'Mexican'),

('Frog Meuniere',
'https://lfuen.github.io/laCarte/images/meals/frog.jpg',
('Fresh Frogs',
'Lemon',
'Olive Oil',
'Lemon',
'Bread',
'Butter',
'White Pepper',
'Fleur du Sel'),
('Joaquin', 'Christian'),
'French'),

('Garides Saganaki (Greek Shrimp Gratin)',
'https://lfuen.github.io/laCarte/images/meals/garides.jpg',
('Olive Oil',
'Onions',
'Garlic',
'Cinnamon',
'Ground Allspice',
'Tomatoes',
'Sugar',
'Shrimp',
'Salt',
'Pepper',
'Feta Cheese',
'Oregano'),
('Johnathan', 'Francesca', 'Joaquin', 'Madelyn'),
'Greek'),

('Gazpacho',
'https://lfuen.github.io/laCarte/images/meals/gazpacho.jpg',
('Tomatoes',
'Cucumber',
'Green Bell Peppers',
'Red Bell Peppers',
'Garlic',
'Onions',
'Bread',
'Extra-Virgin Olive Oil',
'White Vinegar',
'Salt',
'Black Pepper'),
('Johnathan', 'Francesca'),
'Spanish'),

('Greek Bouyourdi: Grilled Feta, Tomato, and Pepper',
'https://lfuen.github.io/laCarte/images/meals/bouyourdi.jpg',
('Tomatoes',
'Feta Cheese',
'Green Bell Peppers',
'Jalapeño Peppers',
'Olive Oil',
'Oregano',
'Bread'),
('Johnathan', 'Francesca', 'Joaquin', 'Madelyn'),
'Greek'),

('Greek Salad',
'https://lfuen.github.io/laCarte/images/meals/greekSalad.jpg',
('Cucumbers',
'Green Bell Peppers',
'Tomatoes',
'Onions',
'Black Olives',
'Green Olives',
'Garlic',
'Feta Cheese',      
'Wine Vinegar',
'Olive Oil',
'Capers',
'Sugar',
'Basil',
'Roman Letttuce'),
('Johnathan', 'Francesca', 'Joaquin', 'Madelyn'),
'Greek'),

('Green Matcha Chicken Curry with Lime',
'https://lfuen.github.io/laCarte/images/meals/matcha.jpg',
('Coriander',
'Cumin',
'Matcha Powder',
'Nutmeg',
'Garlic',
'Shallots',
'Chili Peppers',
'Galangal',
'Lemongrass',
'Kaffir Lime',
'Thai Shrimp Paste',
'Lime',
'Sunflower Oil',
'Chicken',
'Chicken Stock',
'Coconut Milk',
'Mangetout',
'Pak Choi',
'Salt',
'Pepper',
'Coriander Sprigs',
'Lime Wedges',
'Crushed Peppercorn'),
('Johnathan', 'Joaquin', 'Christian', 'Madelyn'),
'Thai'),

('Grilled Tuna Skewers with Orange and Ginger on Couscous',
'https://lfuen.github.io/laCarte/images/meals/grilledTuna.jpg',
('Tuna',
'Ginger',
'Olive Oil',
'Orange',
'Honey',
'Raisins',
'Couscous',
'Carrots',
'Almonds',
'Parsley'),
('Johnathan', 'Joaquin', 'Christian'),
'Middle Eastern'),

('Huevos Rancheros',
'https://lfuen.github.io/laCarte/images/meals/huevos.jpg',
('Olive Oil',
'Onions',
'Garlic',
'Chili Peppers',
'Red Peppers',
'Tomatoes',
'Salt',
'Cheddar',
'Eggs',
'Marjoram',
'Bread'),
('Johnathan', 'Francesca', 'Joaquin', 'Christian', 'Madelyn'),
'Mexican'),

('Kedgeree (Haddock with Rice)',
'https://lfuen.github.io/laCarte/images/meals/kedgeree.jpg',
('Milk',
'Haddock',
'Butter',
'Onions',
'Garlic',
'Curry Powder',
'Rice',
'Parsley'),
('Johnathan', 'Christian', 'Madelyn'),
'Indian'),

('Korean Kimchi',
'https://lfuen.github.io/laCarte/images/meals/kimchi.jpg',
('Cabbage',
'Salt',
'Daikon',
'Scallions',
'Gochugaru',
'Korean Spice',
'Fish Sauce',
'Ginger',
'Garlic',
'Sugar'), 
('Johnathan', 'Francesca', 'Christian', 'Madelyn'),	
'Asian'),

('Lamb Kebabs on Tabbouleh',
'https://lfuen.github.io/laCarte/images/meals/lambKebabs.jpg',
('Bulgar Wheat',
'Vegetable Stock',
'Tomatoes',
'Orange Pepper',
'Chili Peppers',
'Onions',
'Courgette',
'Lemon Juice',
'Parsley',
'Olive Oil',
'Salt',
'Fresh Lamb',
'Red Wine Vinegar',
'Mustard',
'Pepper'),
('Johnathan', 'Joaquin', 'Christian'),	
'Middle Eastern'),

('Mexican Corn and Bean Salad',
'https://lfuen.github.io/laCarte/images/meals/cornBean.jpg',
('Oil',
'Onions',
'Garlic',
'Chilli Pepper',
'Tomatoes',
'Sweetcorn',
'Kidney Beans',
'Parsley',
'Sherry Vinegar',
'Olive Oil',
'Salt',
'Pepper',
'Cherry Tomatoes'),
('Johnathan', 'Francesca', 'Joaquin', 'Christian', 'Madelyn'),
'Mexican'),

('Miso Soup with Tofu, Bean Sprouts, and Herbs',
'https://lfuen.github.io/laCarte/images/meals/misoSoup.jpg',
('Kombu',
'Bonito Flakes',
'Miso Paste',
'Tofu',
'Bean Sprouts',
'Fresh Herbs',
'Chili Sauce'),
('Johnathan', 'Francesca', 'Christian', 'Madelyn'),
'Asian'),

('Nicoise Salad with Fresh Tuna',
'https://lfuen.github.io/laCarte/images/meals/nicoise.jpg',
('Tuna',
'Eggs',
'Purple Potatos',
'Butter Lettuce',
'Tomatoes',
'Thyme',
'Capers',
'Anchovies',      
'Bread',
'Lemon',
'Walnut Oil',
'Extra-Virgin Olive Oil',
'Pepper',
'Green Beans',
'Black Taggiasche Oils'),
('Joaquin', 'Christian'),
'French'),

('Pad Thai Noodles',
'https://lfuen.github.io/laCarte/images/meals/padThai.jpg',
('Rice Noodles',
'Lime Juice',
'Garlic',
'Fish Sauce',
'Brown Sugar',
'Chili Flakes',
'Groundnut Oil',
'Eggs',
'Prawns',
'Peanuts',
'Mustard'),
('Johnathan', 'Joaquin', 'Christian', 'Madelyn'),
'Thai'),

('Patatas Bravas',
'https://lfuen.github.io/laCarte/images/meals/patatas.jpg',
('Potatoes',
'Tomatoes',
'Onions',
'Garlic',
'Tomato Puree',
'Sugar',
'Tobasco Sauce',
'Brown Sugar',
'Oregano',
'Olive Oil',
'Sea Salt'),
('Johnathan', 'Francesca'),
'Spanish'),

('Pide (Turkish Flat Bread) with Sheeps Cheese Filling',
'https://lfuen.github.io/laCarte/images/meals/pide.jpg',
('Flour',
'Yeast',
'Sugar',
'Salt',
'Oil',
'Yogurt',
'Sheeps Cheese',
'Parsley',
'Olive Oil',
'Lemon Juice',
'Garlic'),
('Johnathan', 'Joaquin', 'Christian'),	
'Middle Eastern'),

('Potato Tortilla',
'https://lfuen.github.io/laCarte/images/meals/potatoTortilla.jpg',
('Potatoes',
'Red Peppers',
'Cherry Tomatoes',
'Eggs',
'Milk',
'Parmesan',
'Dill',
'Creme Fraiche',
'Nutmeg',
'Parsley'),
('Johnathan', 'Francesca'),
'Spanish'),

('Ravioli with Gorganzola, Pear, and Walnuts',
'https://lfuen.github.io/laCarte/images/meals/ravioli.jpg',
('Walnuts',
'Ricotta Cheese',
'Olive Oil',
'Parsley',
'Pasta Dough',
'Gorganzola',
'Pear',
'Lemon Juice'),
('Francesca', 'Joaquin'),
'Italian'),

('Red Duck Curry',
'https://lfuen.github.io/laCarte/images/meals/redDuck.jpg',
('Duck',
'Tomatoes',
'Lime',
'Basil',
'Pineapple',
'Oil',
'Red Curry Paste',
'Unsweetened Coconut Milk',
'Fish Sauce',
'Brown Sugar'),
('Johnathan', 'Joaquin', 'Christian', 'Madelyn'),
'Thai'),

('Rigatoni with Veal',
'https://lfuen.github.io/laCarte/images/meals/rigatoni.jpg',
('Veal',
'Carrots',
'Celery',
'Tomatoes',
'Parsley',
'Extra-Virgin Olive Oil',
'Meat Stock',
'Red Wine',
'Onions',
'Garlic',
'Thyme',
'Bayleaves',
'Rosemary',
'Salt',
'Ground Pepper',
'White Beans',
'Rigatoni'),
('Francesca', 'Joaquin'),
'Italian'),

('Roast Lamb with Indian Spices',
'https://lfuen.github.io/laCarte/images/meals/roastLamb.jpg',
('Leg of Lamb',
'Corriander',
'Cumin',
'Onions',
'Garlic',
'Almonds',
'Ginger',
'Green Chiles',
'Salt',
'Yogurt',
'Vegetable Oil',
'Ground Turmeric',
'Cayenne Pepper',
'Garam Masala',
'Cassia Bark'),
('Johnathan', 'Christian', 'Madelyn'),	
'Indian'),

('Roasted Pumpkin and Pear Soup',
'https://lfuen.github.io/laCarte/images/meals/roastedPumpkin.jpg',
('Pear',
'Pumpkin',
'Tomatoes',
'Onions',
'Garlic',
'Olive Oil',
'Salt',
'Pepper',
'Vegetable Broth',
'Chives',
'Fresh Cream'),
('Johnathan',  'Christian', 'Madelyn'),
'American'),

('Salmon Maki Sushi',
'https://lfuen.github.io/laCarte/images/meals/salmonMaki.jpg',
('Salmon',
'Nori Sheets',
'Wasabi Paste',
'Sushi Rice',
'Kombu',
'Vinegar',
'Salt',
'Sugar'),
('Johnathan', 'Francesca', 'Christian', 'Madelyn'),
'Asian'),

('Seared Scallops with Osetra Caviar and Potato-Chive Mousseline',
'https://lfuen.github.io/laCarte/images/meals/scallops.jpg',
('Potatoes',
'Kosher Salt',
'Butter',
'Milk',
'Chives',
'Salt',
'White Pepper',
'Scallops',
'Olive Oil',
'Lemon Juice',
'Osetra Caviar'),
('Johnathan', 'Christian', 'Madelyn'),
'American'),

('Slow-Cooked Beef Short Ribs',
'https://lfuen.github.io/laCarte/images/meals/shortRibs.jpg',
('Beef Short Ribs',
'Salt',
'Oil',
'Olive Oil',
'White Wine Vinegar',
'Parsely',
'Garlic',
'Oregano',
'Chili Peppers'),
('Johnathan', 'Francesca', 'Joaquin'),
'Latin American'),

('Spaghetti Napoli',
'https://lfuen.github.io/laCarte/images/meals/spaghetti.jpg',
('Spaghetti',
'Olive Oil',
'Onions',
'Garlic',
'Celery',
'Red Wine',
'Tomatoes',
'Black Olives',
'Sugar',
'Salt',
'Pepper',
'Basil'),
('Francesca', 'Joaquin'),
'Italian'),

('Spicy Tomato and Carrot Soup with Yogurt and Pistachio Dumplings',
'https://lfuen.github.io/laCarte/images/meals/spicyTomato.jpg',
('Ras el Hanout',
'Yogurt',
'Olive Oil',
'Shallots',
'Chili Peppers',
'Carrot',
'Tomatoes',
'Vegetable Stock',
'Ginger',
'Pistachios',
'Chili Strips'),
('Johnathan', 'Francesca', 'Joaquin', 'Madelyn'),
'Greek'),

('Spinach Quiche',
'https://lfuen.github.io/laCarte/images/meals/spinachQuiche.jpg',
('Salt',
'Butter',
'Eggs',
'Cream Cheese',
'Cream',
'Parmesean Cheese',
'Spinach',
'Garlic',
'Leeks',
'Nutmeg'),
('Joaquin', 'Christian'),
'Spanish'),

('Squash Gnocchi with Butter and Sage',
'https://lfuen.github.io/laCarte/images/meals/squashGnocchi.jpg',
('Potatoes',
'Muscat Squash',
'Nutmeg',
'Olive Oil',
'Parmesan',
'Eggs',
'Flour',
'Butter',
'Sage',
'Garlic'),
('Francesca', 'Joaquin'),
'Italian'),

('Tandoori Duck',
'https://lfuen.github.io/laCarte/images/meals/tandoori.jpg',
('Duck',
'Yogurt',
'Apple Vinegar',
'Sesame Oil',
'Garlic',
'Ginger',
'Coriander',
'Cumin',
'Chili Powder',
'Turmeric',
'Cucumber',
'Ginger',
'Lemon'),
('Johnathan',  'Christian', 'Madelyn'),
'Indian'),

('Thai Spring Rolls',
'https://lfuen.github.io/laCarte/images/meals/thaiRolls.jpg',
('Noodles',
'Carrot',
'Cabbage',
'Bean Sprouts',
'Oil',
'Garlic',
'Minced Beef',
'Salt',
'Pepper',
'Sugar',
'Eggs',
'Thai Sweet Chili Dip'),
('Johnathan', 'Joaquin', 'Christian', 'Madelyn'),
'Thai'),

('Tomato Soup with Goat Cheese Gnudi',
'https://lfuen.github.io/laCarte/images/meals/tomatoGoat.jpg',
('Extra-Virgin Olive Oil',
'Butter',
'Onions',
'Garlic',
'Tomatoes',
'Flour',
'Chicken Broth',
'Plum Tomatoes',
'Sugar',
'Thyme',
'Goat Cheese',
'Parmigiano-Reggiano Cheese',
'Eggs',
'Nutmeg',
'Salt',
'Black Pepper',
'Flour',
'Basil'),
('Francesca', 'Joaquin'),
'Italian'),

('Traditional Falafel',
'https://lfuen.github.io/laCarte/images/meals/falafel.jpg',
('Chickpeas',
'Garlic',
'Onions',
'Coriander',
'Cumin',
'Parsley',
'Salt',
'Lemon Juice',
'Black Pepper',
'Oil'),	
('Johnathan', 'Joaquin', 'Christian'),	
'Middle Eastern'),

('Tuna and Negi Sushi Roll',
'https://lfuen.github.io/laCarte/images/meals/tunaSushi.jpg',
('Rice',
'Kombu',
'Vinegar',
'Nori Sheets',
'Wasabi Pate',
'Fresh Tuna',
'Negi'), 
('Johnathan', 'Francesca', 'Christian', 'Madelyn'),
'Asian'),

('Turkey Burger',
'https://lfuen.github.io/laCarte/images/meals/turkeyBurger.jpg',
('Oil',
'Onions',
'Mushrooms',
'Mixed Herbs',
'Turkey',
'Eggs',
'Lettuce',
'Cranberries'),
('Johnathan', 'Christian', 'Madelyn'),
'American'),

('Wonton Soup',
'https://lfuen.github.io/laCarte/images/meals/wonton.jpg',
('Wonton Wrappers',
'Ginger',
'Garlic',
'Chive',
'Salt',
'Pepper',
'Rice Wine',
'Sesame',
'Eggs',
'Chicken Stock',
'Cabbage',
'Soy Sauce',
'Rice Vinegar',       
'Sichuan Peppers'),	
('Johnathan', 'Francesca', 'Christian','Madelyn'),	
'Asian');

COMMIT;